// <auto-generated />
using System;
using ExpenseClaim.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpenseClaim.Migrations
{
    [DbContext(typeof(ClaimContext))]
    partial class ClaimContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExpenseClaim.Entities.CostCenter", b =>
                {
                    b.Property<string>("CostCenterId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CostCenterName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("IsDefault");

                    b.HasKey("CostCenterId");

                    b.ToTable("CostCenter");
                });

            modelBuilder.Entity("ExpenseClaim.Entities.Expenses", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CostCenterId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<decimal>("Gst");

                    b.Property<string>("PaymentMethod");

                    b.Property<decimal>("TotalAmount");

                    b.Property<DateTime>("TransactionDate");

                    b.Property<string>("Vendor");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ExpenseClaim.Entities.Expenses", b =>
                {
                    b.HasOne("ExpenseClaim.Entities.CostCenter", "CostCenter")
                        .WithMany("Expenses")
                        .HasForeignKey("CostCenterId");
                });
#pragma warning restore 612, 618
        }
    }
}
